### ISSUE TITLE
Sum checking fails

### ISSUE THREAD

**Issue by iby** [ddiachkov/coreos-parallels-packer#1]
Hey Denis. Would be awesome if there was a way to specify the release channel and if the script could lookup MD5 automatically from `coreos_production_iso_image.iso.DIGESTS`. The current version seems already out of date.

**Comment by iby** [comment]
I had to get my hands dirty with packer to get this working, I understand that this is done by packer and the only way to automate this would be by adding an extra logic on top to generate `coreos.json` on the fly. Most people won't need this unless they run it 20 times per day.

**Comment by ddiachkov** [comment]
Hey! It is a good idea.
I'll add Makefile later today to implement this.

(meanwhile you can just change `iso_checksum_type` to `none` to disable checksum checking)

**Comment by iby** [comment]
I thought of doing that, but it said its a required param. Obviously missed the `"iso_checksum_type": "none"` part. Thanks man!

**Comment by ddiachkov** [comment]
Ok, I've added new Makefile. You can now build alpha/beta/stable CoreOS this way:

``` shell
make coreos COREOS_RELEASE=alpha
```

Or if you prefer to call Packer directly:

``` shell
packer build -force -var "coreos-release=alpha" coreos.json
```

(NB: if you call packer directly checksum will not be verified)

**Comment by iby** [comment]
Thanks man! Trying it out now. I've been playing with it today and getting inconsistent results, one time it installs, the other time it fails. Something doesn't get right inside the coreos. This just failed on alpha again, which installed ok earlier in the day, but beta got installed correctly. Anyway. Thanks for the effort!

```
==> parallels-iso: Provisioning with shell script: /var/folders/w3/zytpgjm11557jppm2zbg8xmh0000gq/T/packer-shell610463475
    parallels-iso: Checking availability of "local-file"
    parallels-iso: Fetching user-data from datasource of type "local-file"
    parallels-iso: Downloading the signature for http://alpha.release.core-os.net/amd64-usr/695.0.0/coreos_production_image.bin.bz2...
    parallels-iso: 2015-06-03 16:59:11 URL:http://alpha.release.core-os.net/amd64-usr/695.0.0/coreos_production_image.bin.bz2.sig [543/543] -> "/tmp/coreos-install.3N907fQmMH/coreos_production_image.bin.bz2.sig" [1]
    parallels-iso: Downloading, writing and verifying coreos_production_image.bin.bz2...
    parallels-iso: 2015-06-03 17:04:36 URL:http://alpha.release.core-os.net/amd64-usr/695.0.0/coreos_production_image.bin.bz2 [199486728/199486728] -> "-" [1]
    parallels-iso: gpg: Signature made Thu May 28 00:49:34 2015 UTC using RSA key ID E5676EFC
    parallels-iso: gpg: key 93D2DCB4 marked as ultimately trusted
    parallels-iso: gpg: checking the trustdb
    parallels-iso: gpg: 3 marginal(s) needed, 1 complete(s) needed, PGP trust model
    parallels-iso: gpg: depth: 0  valid:   1  signed:   0  trust: 0-, 0q, 0n, 0m, 0f, 1u
    parallels-iso: gpg: Good signature from "CoreOS Buildbot (Offical Builds) <buildbot@coreos.com>" [ultimate]
    parallels-iso: Installing cloud-config...
    parallels-iso: cp: cannot create regular file '/tmp/coreos-install.3N907fQmMH/rootfs/var/lib/coreos-install/user_data': No such file or directory
    parallels-iso: umount: /tmp/coreos-install.3N907fQmMH/rootfs: not mounted
==> parallels-iso: Unregistering virtual machine...
==> parallels-iso: Deleting output directory...
Build 'parallels-iso' errored: Script exited with non-zero exit status: 1
```
